% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Data Visualization Bootcamp Homework},
  pdfauthor={Dhanachote Not},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Data Visualization Bootcamp Homework}
\author{Dhanachote Not}
\date{2023-07-03}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Hi my name is Dhanachote, you can call me by my nickname is Not. I am
learning how to use rmarkdown and build my first Data Visualization. By
the way, this report is for homework using ggplot2 to create data
visualization to build in dataset ``diamonds'' in R studio with five
questions.

\hypertarget{rmarkdown-cheat-sheet}{%
\subsection{rmarkdown-cheat sheet}\label{rmarkdown-cheat-sheet}}

I would like to share rmarkdown-cheat sheet for everyone use their own
project or homework!

\href{https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf}{rmarkdown-cheatsheet}

\hypertarget{minimize-dataset-before-making-the-data-visualization}{%
\subsubsection{Minimize dataset before making the Data
Visualization}\label{minimize-dataset-before-making-the-data-visualization}}

The dataset of diamonds it has 53,940 rows that it can be working with
this dataset are not comfortable because it can be running the result
slower. So, i will random 10 percents of all samples before marking data
visualization.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# load library}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyverse' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'tibble' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'tidyr' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'readr' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'purrr' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'stringr' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'forcats' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'lubridate' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.2     v readr     2.1.4
## v forcats   1.0.0     v stringr   1.5.0
## v ggplot2   3.4.2     v tibble    3.2.1
## v lubridate 1.9.2     v tidyr     1.3.0
## v purrr     1.0.1     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggthemes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggthemes' was built under R version 4.3.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# lock random sample for use dataset}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{42}\NormalTok{)}
\NormalTok{sample\_diamonds }\OtherTok{\textless{}{-}} \FunctionTok{sample\_frac}\NormalTok{(diamonds, }\FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{question-1}{%
\paragraph{\texorpdfstring{\textbf{Question
1}}{Question 1}}\label{question-1}}

\textbf{How dose the price of diamonds vary with carat weight?}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(sample\_diamonds, }\FunctionTok{aes}\NormalTok{(carat, price, }\AttributeTok{col =}\NormalTok{ cut)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha  =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_calc}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{type =} \StringTok{"seq"}\NormalTok{,}
                     \AttributeTok{palette =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship between carat and price"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"carat weight"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"price"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Source: Dataset diamonds in Rstudio"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\includegraphics{homework_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(sample\_diamonds}\SpecialCharTok{$}\NormalTok{carat, sample\_diamonds}\SpecialCharTok{$}\NormalTok{price)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9212468
\end{verbatim}

From this plot, we found that the price of diamonds varies with carat
weight using correlation = 0.9180853 which means the higher carat might
have a higher price.

\hypertarget{question-2}{%
\subparagraph{\texorpdfstring{\textbf{Question
2}}{Question 2}}\label{question-2}}

\textbf{What is the distribution of diamond prices based on their cut
quality?}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(sample\_diamonds, }\FunctionTok{aes}\NormalTok{(cut, price, }\AttributeTok{col =}\NormalTok{ cut)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{( }\AttributeTok{type =} \StringTok{"seq"}\NormalTok{,}
                      \AttributeTok{palette =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship between cut and price"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"cut quality"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"price"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Source: Data set diamonds in Rstudio"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\includegraphics{homework_files/figure-latex/unnamed-chunk-3-1.pdf}

As you can see the relationship between cut and price. A cut quality has
a five level is fair, good, very good, premium and ideal as a X-axis,
and Y is price. In chart show that higher cut quality it will be higher
price

\hypertarget{question-3}{%
\subparagraph{\texorpdfstring{\textbf{Question
3}}{Question 3}}\label{question-3}}

\textbf{How does the relationship between diamond price and carat weight
differ across different color grades?}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(sample\_diamonds, }
       \FunctionTok{aes}\NormalTok{(carat, price, }\AttributeTok{col =}\NormalTok{ color)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relaitonship between carat and price"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"across different color grades"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"carat"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"price"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Source: Dataset diamonds in Rstudio"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ cut)}
\end{Highlighting}
\end{Shaded}

\includegraphics{homework_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# filter level of carat and price by color}

\NormalTok{sample\_diamonds }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(cut, carat, price, color) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(color) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(carat }\SpecialCharTok{\textgreater{}} \DecValTok{3}\NormalTok{, price }\SpecialCharTok{\textgreater{}=} \DecValTok{10000}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
## # Groups:   color [3]
##   cut     carat price color
##   <ord>   <dbl> <int> <ord>
## 1 Fair     3.01 18242 I    
## 2 Premium  3.01 18710 J    
## 3 Premium  3.01 18710 J    
## 4 Fair     3.4  15964 D
\end{verbatim}

In this chart, it show how does the relationship between diamond price
and carat weight by color grades. I decide use
\texttt{facet\_wrap(\textasciitilde{}\ cut)} show the chart easier for
understanding that the price will be increasing by color in every level
of cut. In the summary, Ideal are the highest price in 3.01 carat weight
by J color.

\hypertarget{question-4}{%
\subparagraph{\texorpdfstring{\textbf{Question
4}}{Question 4}}\label{question-4}}

\textbf{Can we observe any relationship between diamond price and
clarity?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{agg\_price\_by\_clarity }\OtherTok{\textless{}{-}}\NormalTok{ sample\_diamonds }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(clarity) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{med\_price =} \FunctionTok{median}\NormalTok{(price)}
\NormalTok{  )}


\FunctionTok{ggplot}\NormalTok{(agg\_price\_by\_clarity,}
       \FunctionTok{aes}\NormalTok{(clarity, med\_price, }\AttributeTok{fill =}\NormalTok{ clarity)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_calc}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_brewer}\NormalTok{( }\AttributeTok{type =} \StringTok{"qua"}\NormalTok{,}
                      \AttributeTok{palette  =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relaitonship between diamond price and clarity"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"clarity"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"price"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Source: Dataset diamonds in Rstudio"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\includegraphics{homework_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# median diamonds sample price}

\FunctionTok{median}\NormalTok{(sample\_diamonds}\SpecialCharTok{$}\NormalTok{price)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2415
\end{verbatim}

In this bar chart \texttt{geom\_col()} will explain the relationship
between diamond price and clarity. They have SI2 clarity is the highest
price followed by I1 and SI1. Also, the median of sample diamonds is
2,415.

\hypertarget{question-5}{%
\subparagraph{\texorpdfstring{\textbf{Question
5}}{Question 5}}\label{question-5}}

\textbf{What is the distribution of diamond prices based on their cut
and color grades?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{agg\_price\_by\_cut\_color }\OtherTok{\textless{}{-}}\NormalTok{ sample\_diamonds }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(cut, color) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{med\_price =} \FunctionTok{median}\NormalTok{(price)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'cut'. You can override using the `.groups`
## argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(agg\_price\_by\_cut\_color, }\FunctionTok{aes}\NormalTok{(cut, color, }\AttributeTok{fill =}\NormalTok{ med\_price)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient}\NormalTok{(}\AttributeTok{low =} \StringTok{"\#fec89a"}\NormalTok{, }\AttributeTok{high =} \StringTok{"\#ff7900"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Distribution of Diamond Prices by Cut and Color"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Cut"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Color"}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"Median Price"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ cut, }\AttributeTok{ncol =} \DecValTok{3}\NormalTok{, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{homework_files/figure-latex/unnamed-chunk-6-1.pdf}

In this chart is distribution of diamonds prices based on their cut and
color grades. If you see on the heatmap chart, it show level of cut
relationship with color and distribution by average price.

\hypertarget{summary}{%
\section{Summary}\label{summary}}

In this report, I learn a lot of \texttt{geom} chart, how to create my
data visualization with the dataset by diamonds and use rmarkdown to
build web or export file to PDF. Thank you.

\includegraphics{https://contenthub-static.grammarly.com/blog/wp-content/uploads/2019/02/bmd-4584.png}

\end{document}
